//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02___ApiRepositorio.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int idPersona { get; set; }
        public int idDireccion { get; set; }
    
        public virtual Direccion Direccion { get; set; }
    }
}
